### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32')

### ISSUE THREAD

**Issue by hwmaybe** [ClementPinard/Pytorch-SiamFC#36]
When I want to train the model by run the below command:
               python train.py --data_dir /home/whw/Tracking/Pytorch-SiamFC/ILSVRC --exp_name fc -f safe
The output is listed as follow:
[IMAGE-UTILS] package jpeg4py not available. Continuing...
----Starting train script in mode: train----
Loading datasets...
Validation dataset...
Metadata file found. Loading its content.
Training dataset...
Metadata file found. Loading its content.
The user set train_epoch_size (10000) is bigger than the size of the train set (6280). 
 Setting train_epoch_size to the train set size.
Done
Setup time: 0h0m1.56s
Using Exponential Learning Rate Decay of 1
Epoch sizes: 6280 in train and 10000 in eval
Starting training for 1 epoch(s)
Pretraining evaluation...
Validation on val set
  0%|                                                                                                                                              | 0/10000 [00:00<?, ?it/s]Saving embeddings for summary 0
Saving embeddings for summary 1
Saving embeddings for summary 2
Saving embeddings for summary 3
Saving embeddings for summary 4
  0%|                                                                                                                                              | 0/10000 [00:03<?, ?it/s]
Fatal error in main loop
Traceback (most recent call last):
  File "train.py", line 193, in main
    args, summ_maker=summ_maker)
  File "train.py", line 271, in train_and_evaluate
    summ_maker=summ_maker)
  File "/home/whw/anaconda3/envs/siamfc/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 46, in decorate_no_grad
    return func(*args, **kwargs)
  File "train.py", line 496, in evaluate
    for metric_name, metric_dict in metrics.items()}
  File "train.py", line 496, in <dictcomp>
    for metric_name, metric_dict in metrics.items()}
  File "/home/whw/Tracking/Pytorch-SiamFC/training/metrics.py", line 60, in AUC
    if np.isnan(label[i]) or np.isnan(output[i]):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
=== Execution Terminated with error ===
Who can help me?

**Comment by hwmaybe** [comment]
I solved it! Refer to my commit.
